/**
 * Language Configuration
 * 
 * Separates transcription languages (Google Speech-to-Text) from translation languages (GPT-4o-mini)
 * 
 * TRANSCRIPTION: Limited to Google Speech-to-Text supported languages (71 languages)
 * TRANSLATION: Maximum possible languages supported by GPT-4o-mini (100+ languages)
 * 
 * ORDER: Top 10 languages first, then alphabetical
 */

// Top 10 most common languages (shown first)
const TOP_LANGUAGES = ['en', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ja', 'ko', 'zh'];

// Google Speech-to-Text supported languages (71 languages)
// These can be used for BOTH transcription and translation
export const TRANSCRIPTION_LANGUAGES = {
  // Top 10 languages first
  'en': { code: 'en-US', name: 'English (General)' },
  'en-US': { code: 'en-US', name: 'English (US)' },
  'en-GB': { code: 'en-GB', name: 'English (UK)' },
  'en-AU': { code: 'en-AU', name: 'English (Australia)' },
  'en-IN': { code: 'en-IN', name: 'English (India)' },
  'es': { code: 'es-ES', name: 'Spanish (Spain)' },
  'es-MX': { code: 'es-MX', name: 'Spanish (Mexico)' },
  'es-US': { code: 'es-US', name: 'Spanish (US)' },
  'es-419': { code: 'es-419', name: 'Spanish (Latin America)' },
  'fr': { code: 'fr-FR', name: 'French (France)' },
  'fr-CA': { code: 'fr-CA', name: 'French (Canada)' },
  'de': { code: 'de-DE', name: 'German' },
  'it': { code: 'it-IT', name: 'Italian' },
  'pt': { code: 'pt-PT', name: 'Portuguese (Portugal)' },
  'pt-BR': { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  'ru': { code: 'ru-RU', name: 'Russian' },
  'ja': { code: 'ja-JP', name: 'Japanese' },
  'ko': { code: 'ko-KR', name: 'Korean' },
  'zh': { code: 'zh-CN', name: 'Chinese (Simplified)' },
  'zh-TW': { code: 'zh-TW', name: 'Chinese (Traditional)' },

  // Rest alphabetically
  'af': { code: 'af-ZA', name: 'Afrikaans' },
  'am': { code: 'am-ET', name: 'Amharic' },
  'ar': { code: 'ar-SA', name: 'Arabic (General)' },
  'ar-EG': { code: 'ar-EG', name: 'Arabic (Egypt)' },
  'ar-XA': { code: 'ar-XA', name: 'Arabic (Standard)' },
  'az': { code: 'az-AZ', name: 'Azerbaijani' },
  'be': { code: 'be-BY', name: 'Belarusian' },
  'bn': { code: 'bn-IN', name: 'Bengali' },
  'bn-BD': { code: 'bn-BD', name: 'Bengali (Bangladesh)' },
  'bn-IN': { code: 'bn-IN', name: 'Bengali (India)' },
  'bs': { code: 'bs-BA', name: 'Bosnian' },
  'bg': { code: 'bg-BG', name: 'Bulgarian' },
  'ca': { code: 'ca-ES', name: 'Catalan' },
  'cnr': { code: 'cnr-ME', name: 'Montenegrin' },
  'cs': { code: 'cs-CZ', name: 'Czech' },
  'da': { code: 'da-DK', name: 'Danish' },
  'et': { code: 'et-EE', name: 'Estonian' },
  'eu': { code: 'eu-ES', name: 'Basque' },
  'fa': { code: 'fa-IR', name: 'Persian' },
  'fil': { code: 'fil-PH', name: 'Filipino' },
  'fi': { code: 'fi-FI', name: 'Finnish' },
  'ga': { code: 'ga-IE', name: 'Irish' },
  'gl': { code: 'gl-ES', name: 'Galician' },
  'el': { code: 'el-GR', name: 'Greek' },
  'gu': { code: 'gu-IN', name: 'Gujarati' },
  'ha': { code: 'ha-NG', name: 'Hausa' },
  'he': { code: 'he-IL', name: 'Hebrew' },
  'hi': { code: 'hi-IN', name: 'Hindi' },
  'hr': { code: 'hr-HR', name: 'Croatian' },
  'ht': { code: 'ht-HT', name: 'Haitian Creole' },
  'hu': { code: 'hu-HU', name: 'Hungarian' },
  'id': { code: 'id-ID', name: 'Indonesian' },
  'ig': { code: 'ig-NG', name: 'Igbo' },
  'is': { code: 'is-IS', name: 'Icelandic' },
  'jw': { code: 'jw-ID', name: 'Javanese' },
  'ka': { code: 'ka-GE', name: 'Georgian' },
  'kk': { code: 'kk-KZ', name: 'Kazakh' },
  'km': { code: 'km-KH', name: 'Khmer' },
  'kn': { code: 'kn-IN', name: 'Kannada' },
  'rw': { code: 'rw-RW', name: 'Kinyarwanda' },
  'ky': { code: 'ky-KG', name: 'Kyrgyz' },
  'lb': { code: 'lb-LU', name: 'Luxembourgish' },
  'lo': { code: 'lo-LA', name: 'Lao' },
  'lt': { code: 'lt-LT', name: 'Lithuanian' },
  'lv': { code: 'lv-LV', name: 'Latvian' },
  'mk': { code: 'mk-MK', name: 'Macedonian' },
  'ml': { code: 'ml-IN', name: 'Malayalam' },
  'ms': { code: 'ms-MY', name: 'Malay' },
  'mt': { code: 'mt-MT', name: 'Maltese' },
  'mr': { code: 'mr-IN', name: 'Marathi' },
  'mn': { code: 'mn-MN', name: 'Mongolian' },
  'ne': { code: 'ne-NP', name: 'Nepali' },
  'nl': { code: 'nl-NL', name: 'Dutch (Netherlands)' },
  'nl-BE': { code: 'nl-BE', name: 'Dutch (Belgium)' },
  'no': { code: 'no-NO', name: 'Norwegian' },
  'pa': { code: 'pa-IN', name: 'Punjabi' },
  'ps': { code: 'ps-AF', name: 'Pashto' },
  'pl': { code: 'pl-PL', name: 'Polish' },
  'ro': { code: 'ro-RO', name: 'Romanian' },
  'si': { code: 'si-LK', name: 'Sinhala' },
  'sk': { code: 'sk-SK', name: 'Slovak' },
  'sl': { code: 'sl-SI', name: 'Slovenian' },
  'so': { code: 'so-SO', name: 'Somali' },
  'sq': { code: 'sq-AL', name: 'Albanian' },
  'sr': { code: 'sr-RS', name: 'Serbian' },
  'su': { code: 'su-ID', name: 'Sundanese' },
  'sv': { code: 'sv-SE', name: 'Swedish' },
  'sw': { code: 'sw-KE', name: 'Swahili' },
  'ta': { code: 'ta-IN', name: 'Tamil' },
  'te': { code: 'te-IN', name: 'Telugu' },
  'th': { code: 'th-TH', name: 'Thai' },
  'tl': { code: 'tl-PH', name: 'Tagalog' },
  'tr': { code: 'tr-TR', name: 'Turkish' },
  'uk': { code: 'uk-UA', name: 'Ukrainian' },
  'ur': { code: 'ur-PK', name: 'Urdu' },
  'ur-PK': { code: 'ur-PK', name: 'Urdu (Pakistan)' },
  'ur-IN': { code: 'ur-IN', name: 'Urdu (India)' },
  'uz': { code: 'uz-UZ', name: 'Uzbek' },
  'vi': { code: 'vi-VN', name: 'Vietnamese' },
  'cy': { code: 'cy-GB', name: 'Welsh' },
  'xh': { code: 'xh-ZA', name: 'Xhosa' },
  'yo': { code: 'yo-NG', name: 'Yoruba' },
  'zu': { code: 'zu-ZA', name: 'Zulu' }
};

// Comprehensive translation languages (100+ languages)
// Includes all transcription languages PLUS additional languages GPT-4o-mini can translate
export const TRANSLATION_LANGUAGES = {
  // Top 10 languages first
  'en': { code: 'en-US', name: 'English (General)' },
  'en-US': { code: 'en-US', name: 'English (US)' },
  'en-GB': { code: 'en-GB', name: 'English (UK)' },
  'en-AU': { code: 'en-AU', name: 'English (Australia)' },
  'en-IN': { code: 'en-IN', name: 'English (India)' },
  'es': { code: 'es-ES', name: 'Spanish (Spain)' },
  'es-MX': { code: 'es-MX', name: 'Spanish (Mexico)' },
  'es-US': { code: 'es-US', name: 'Spanish (US)' },
  'es-419': { code: 'es-419', name: 'Spanish (Latin America)' },
  'fr': { code: 'fr-FR', name: 'French (France)' },
  'fr-CA': { code: 'fr-CA', name: 'French (Canada)' },
  'de': { code: 'de-DE', name: 'German' },
  'it': { code: 'it-IT', name: 'Italian' },
  'pt': { code: 'pt-PT', name: 'Portuguese (Portugal)' },
  'pt-BR': { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  'ru': { code: 'ru-RU', name: 'Russian' },
  'ja': { code: 'ja-JP', name: 'Japanese' },
  'ko': { code: 'ko-KR', name: 'Korean' },
  'zh': { code: 'zh-CN', name: 'Chinese (Simplified)' },
  'zh-TW': { code: 'zh-TW', name: 'Chinese (Traditional)' },

  // All other languages merged and sorted alphabetically
  'aa': { code: 'aa', name: 'Afar' },
  'ab': { code: 'ab', name: 'Abkhazian' },
  'ae': { code: 'ae', name: 'Avestan' },
  'af': { code: 'af-ZA', name: 'Afrikaans' },
  'ak': { code: 'ak', name: 'Akan' },
  'am': { code: 'am-ET', name: 'Amharic' },
  'an': { code: 'an', name: 'Aragonese' },
  'ar': { code: 'ar-SA', name: 'Arabic (General)' },
  'ar-EG': { code: 'ar-EG', name: 'Arabic (Egypt)' },
  'ar-XA': { code: 'ar-XA', name: 'Arabic (Standard)' },
  'as': { code: 'as', name: 'Assamese' },
  'av': { code: 'av', name: 'Avaric' },
  'ay': { code: 'ay', name: 'Aymara' },
  'az': { code: 'az-AZ', name: 'Azerbaijani' },
  'ba': { code: 'ba', name: 'Bashkir' },
  'be': { code: 'be-BY', name: 'Belarusian' },
  'bg': { code: 'bg-BG', name: 'Bulgarian' },
  'bh': { code: 'bh', name: 'Bihari' },
  'bi': { code: 'bi', name: 'Bislama' },
  'bn': { code: 'bn-IN', name: 'Bengali' },
  'bo': { code: 'bo', name: 'Tibetan' },
  'br': { code: 'br', name: 'Breton' },
  'bs': { code: 'bs-BA', name: 'Bosnian' },
  'ca': { code: 'ca-ES', name: 'Catalan' },
  'ch': { code: 'ch', name: 'Chamorro' },
  'cnr': { code: 'cnr-ME', name: 'Montenegrin' },
  'co': { code: 'co', name: 'Corsican' },
  'cr': { code: 'cr', name: 'Cree' },
  'cs': { code: 'cs-CZ', name: 'Czech' },
  'cu': { code: 'cu', name: 'Church Slavic' },
  'cv': { code: 'cv', name: 'Chuvash' },
  'cy': { code: 'cy-GB', name: 'Welsh' },
  'da': { code: 'da-DK', name: 'Danish' },
  'dv': { code: 'dv', name: 'Dhivehi' },
  'dz': { code: 'dz', name: 'Dzongkha' },
  'ee': { code: 'ee', name: 'Ewe' },
  'el': { code: 'el-GR', name: 'Greek' },
  'eo': { code: 'eo', name: 'Esperanto' },
  'et': { code: 'et-EE', name: 'Estonian' },
  'eu': { code: 'eu-ES', name: 'Basque' },
  'fa': { code: 'fa-IR', name: 'Persian' },
  'fi': { code: 'fi-FI', name: 'Finnish' },
  'fil': { code: 'fil-PH', name: 'Filipino' },
  'fo': { code: 'fo', name: 'Faroese' },
  'fy': { code: 'fy', name: 'Western Frisian' },
  'ga': { code: 'ga-IE', name: 'Irish' },
  'gd': { code: 'gd', name: 'Scottish Gaelic' },
  'gl': { code: 'gl-ES', name: 'Galician' },
  'gn': { code: 'gn', name: 'Guarani' },
  'gu': { code: 'gu-IN', name: 'Gujarati' },
  'gv': { code: 'gv', name: 'Manx' },
  'ha': { code: 'ha-NG', name: 'Hausa' },
  'he': { code: 'he-IL', name: 'Hebrew' },
  'hi': { code: 'hi-IN', name: 'Hindi' },
  'hr': { code: 'hr-HR', name: 'Croatian' },
  'ht': { code: 'ht-HT', name: 'Haitian Creole' },
  'hu': { code: 'hu-HU', name: 'Hungarian' },
  'hz': { code: 'hz', name: 'Herero' },
  'ia': { code: 'ia', name: 'Interlingua' },
  'id': { code: 'id-ID', name: 'Indonesian' },
  'ie': { code: 'ie', name: 'Interlingue' },
  'ig': { code: 'ig-NG', name: 'Igbo' },
  'ik': { code: 'ik', name: 'Inupiaq' },
  'io': { code: 'io', name: 'Ido' },
  'is': { code: 'is-IS', name: 'Icelandic' },
  'iu': { code: 'iu', name: 'Inuktitut' },
  'jw': { code: 'jw-ID', name: 'Javanese' },
  'ka': { code: 'ka-GE', name: 'Georgian' },
  'kg': { code: 'kg', name: 'Kongo' },
  'ki': { code: 'ki', name: 'Kikuyu' },
  'kj': { code: 'kj', name: 'Kuanyama' },
  'kk': { code: 'kk-KZ', name: 'Kazakh' },
  'km': { code: 'km-KH', name: 'Khmer' },
  'kn': { code: 'kn-IN', name: 'Kannada' },
  'kr': { code: 'kr', name: 'Kanuri' },
  'ks': { code: 'ks', name: 'Kashmiri' },
  'ku': { code: 'ku', name: 'Kurdish' },
  'kv': { code: 'kv', name: 'Komi' },
  'kw': { code: 'kw', name: 'Cornish' },
  'ky': { code: 'ky-KG', name: 'Kyrgyz' },
  'la': { code: 'la', name: 'Latin' },
  'lb': { code: 'lb-LU', name: 'Luxembourgish' },
  'lg': { code: 'lg', name: 'Ganda' },
  'li': { code: 'li', name: 'Limburgish' },
  'ln': { code: 'ln', name: 'Lingala' },
  'lo': { code: 'lo-LA', name: 'Lao' },
  'lt': { code: 'lt-LT', name: 'Lithuanian' },
  'lu': { code: 'lu', name: 'Luba-Katanga' },
  'lv': { code: 'lv-LV', name: 'Latvian' },
  'mg': { code: 'mg', name: 'Malagasy' },
  'mh': { code: 'mh', name: 'Marshallese' },
  'mi': { code: 'mi', name: 'Maori' },
  'mk': { code: 'mk-MK', name: 'Macedonian' },
  'ml': { code: 'ml-IN', name: 'Malayalam' },
  'mn': { code: 'mn-MN', name: 'Mongolian' },
  'mr': { code: 'mr-IN', name: 'Marathi' },
  'ms': { code: 'ms-MY', name: 'Malay' },
  'mt': { code: 'mt-MT', name: 'Maltese' },
  'na': { code: 'na', name: 'Nauru' },
  'nd': { code: 'nd', name: 'North Ndebele' },
  'ne': { code: 'ne-NP', name: 'Nepali' },
  'ng': { code: 'ng', name: 'Ndonga' },
  'nl': { code: 'nl-NL', name: 'Dutch' },
  'nn': { code: 'nn', name: 'Norwegian Nynorsk' },
  'no': { code: 'no-NO', name: 'Norwegian' },
  'nr': { code: 'nr', name: 'South Ndebele' },
  'nv': { code: 'nv', name: 'Navajo' },
  'ny': { code: 'ny', name: 'Chichewa' },
  'oc': { code: 'oc', name: 'Occitan' },
  'oj': { code: 'oj', name: 'Ojibwa' },
  'om': { code: 'om', name: 'Oromo' },
  'os': { code: 'os', name: 'Ossetian' },
  'pa': { code: 'pa-IN', name: 'Punjabi' },
  'pi': { code: 'pi', name: 'Pali' },
  'pl': { code: 'pl-PL', name: 'Polish' },
  'ps': { code: 'ps-AF', name: 'Pashto' },
  'pt-BR': { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  'qu': { code: 'qu', name: 'Quechua' },
  'rm': { code: 'rm', name: 'Romansh' },
  'rn': { code: 'rn', name: 'Rundi' },
  'ro': { code: 'ro-RO', name: 'Romanian' },
  'rw': { code: 'rw-RW', name: 'Kinyarwanda' },
  'sc': { code: 'sc', name: 'Sardinian' },
  'sd': { code: 'sd', name: 'Sindhi' },
  'se': { code: 'se', name: 'Northern Sami' },
  'sg': { code: 'sg', name: 'Sango' },
  'si': { code: 'si-LK', name: 'Sinhala' },
  'sk': { code: 'sk-SK', name: 'Slovak' },
  'sl': { code: 'sl-SI', name: 'Slovenian' },
  'sn': { code: 'sn', name: 'Shona' },
  'so': { code: 'so-SO', name: 'Somali' },
  'sq': { code: 'sq-AL', name: 'Albanian' },
  'sr': { code: 'sr-RS', name: 'Serbian' },
  'ss': { code: 'ss', name: 'Swati' },
  'st': { code: 'st', name: 'Southern Sotho' },
  'su': { code: 'su-ID', name: 'Sundanese' },
  'sv': { code: 'sv-SE', name: 'Swedish' },
  'sw': { code: 'sw-KE', name: 'Swahili' },
  'ta': { code: 'ta-IN', name: 'Tamil' },
  'te': { code: 'te-IN', name: 'Telugu' },
  'th': { code: 'th-TH', name: 'Thai' },
  'tk': { code: 'tk', name: 'Turkmen' },
  'tl': { code: 'tl-PH', name: 'Tagalog' },
  'tn': { code: 'tn', name: 'Tswana' },
  'to': { code: 'to', name: 'Tonga' },
  'tr': { code: 'tr-TR', name: 'Turkish' },
  'ts': { code: 'ts', name: 'Tsonga' },
  'tt': { code: 'tt', name: 'Tatar' },
  'tw': { code: 'tw', name: 'Twi' },
  'ty': { code: 'ty', name: 'Tahitian' },
  'ug': { code: 'ug', name: 'Uyghur' },
  'uk': { code: 'uk-UA', name: 'Ukrainian' },
  'ur': { code: 'ur-PK', name: 'Urdu' },
  'uz': { code: 'uz-UZ', name: 'Uzbek' },
  've': { code: 've', name: 'Venda' },
  'vi': { code: 'vi-VN', name: 'Vietnamese' },
  'vo': { code: 'vo', name: 'Volapük' },
  'wa': { code: 'wa', name: 'Walloon' },
  'wo': { code: 'wo', name: 'Wolof' },
  'xh': { code: 'xh-ZA', name: 'Xhosa' },
  'yi': { code: 'yi', name: 'Yiddish' },
  'yo': { code: 'yo-NG', name: 'Yoruba' },
  'za': { code: 'za', name: 'Zhuang' },
  'zh-HK': { code: 'zh-HK', name: 'Chinese (Hong Kong)' },
  'zh-SG': { code: 'zh-SG', name: 'Chinese (Singapore)' },
  'zh-TW': { code: 'zh-TW', name: 'Chinese (Traditional)' },
  'zu': { code: 'zu-ZA', name: 'Zulu' }
};

// Helper functions
export function isTranscriptionSupported(langCode) {
  return langCode in TRANSCRIPTION_LANGUAGES;
}

export function isTranslationSupported(langCode) {
  return langCode in TRANSLATION_LANGUAGES;
}

export function getTranscriptionLanguageCode(langCode) {
  const lang = TRANSCRIPTION_LANGUAGES[langCode] || TRANSCRIPTION_LANGUAGES[langCode.split('-')[0]];
  return lang ? lang.code : 'en-US';
}

// Maps our internal language codes to the exact BCP-47 codes Google STT V1 requires
// for alternativeLanguageCodes. Some languages use non-standard codes in Google's API
// (e.g. zh-CN is not accepted; cmn-Hans-CN is required).
const GOOGLE_STT_ALT_CODE_MAP = {
  'zh-CN': 'cmn-Hans-CN',
  'zh-TW': 'cmn-Hant-TW',
};

export function getGoogleSttAltCode(sttCode) {
  return GOOGLE_STT_ALT_CODE_MAP[sttCode] || sttCode;
}

export function getLanguageName(langCode) {
  const lang = TRANSLATION_LANGUAGES[langCode] || TRANSLATION_LANGUAGES[langCode.split('-')[0]];
  return lang ? lang.name : langCode;
}

// Export language lists as arrays for frontend (maintains order: top 10 first, then alphabetical)
export const TRANSCRIPTION_LANGUAGES_ARRAY = Object.entries(TRANSCRIPTION_LANGUAGES).map(([code, data]) => ({
  code,
  name: data.name
}));

export const TRANSLATION_LANGUAGES_ARRAY = Object.entries(TRANSLATION_LANGUAGES).map(([code, data]) => ({
  code,
  name: data.name
}));
