
const FULL_FALLBACK_VOICES = {
    "af-ZA": { "standard": "af-ZA-Standard-A" },
    "am-ET": { "standard": "am-ET-Standard-A", "neural2": "am-ET-Wavenet-A" },
    "ar-XA": { "standard": "ar-XA-Standard-A", "neural2": "ar-XA-Wavenet-A", "chirp3_hd": "ar-XA-Chirp3-HD-Kore" },
    "bg-BG": { "standard": "bg-BG-Standard-A" },
    "bn-IN": { "standard": "bn-IN-Standard-A", "neural2": "bn-IN-Wavenet-A", "chirp3_hd": "bn-IN-Chirp3-HD-Kore" },
    "ca-ES": { "standard": "ca-ES-Standard-A" },
    "cmn-CN": { "standard": "cmn-CN-Standard-A", "neural2": "cmn-CN-Wavenet-A", "chirp3_hd": "cmn-CN-Chirp3-HD-Kore" },
    "cmn-TW": { "standard": "cmn-TW-Standard-A", "neural2": "cmn-TW-Wavenet-A", "chirp3_hd": "cmn-TW-Chirp3-HD-Kore" },
    "cs-CZ": { "standard": "cs-CZ-Standard-A", "neural2": "cs-CZ-Wavenet-A" },
    "da-DK": { "standard": "da-DK-Standard-A", "neural2": "da-DK-Neural2-D", "chirp3_hd": "da-DK-Chirp3-HD-Kore" },
    "de-DE": { "standard": "de-DE-Standard-A", "neural2": "de-DE-Neural2-A", "chirp3_hd": "de-DE-Chirp3-HD-Kore" },
    "el-GR": { "standard": "el-GR-Standard-A", "neural2": "el-GR-Wavenet-A" },
    "en-AU": { "standard": "en-AU-Standard-A", "neural2": "en-AU-Neural2-A", "chirp3_hd": "en-AU-Chirp3-HD-Kore" },
    "en-GB": { "standard": "en-GB-Standard-A", "neural2": "en-GB-Neural2-A", "chirp3_hd": "en-GB-Chirp3-HD-Kore" },
    "en-IN": { "standard": "en-IN-Standard-A", "neural2": "en-IN-Neural2-A", "chirp3_hd": "en-IN-Chirp3-HD-Kore" },
    "en-US": { "standard": "en-US-Standard-A", "neural2": "en-US-Neural2-A", "chirp3_hd": "en-US-Chirp3-HD-Kore" },
    "es-ES": { "standard": "es-ES-Standard-A", "neural2": "es-ES-Neural2-A", "chirp3_hd": "es-ES-Chirp3-HD-Kore" },
    "es-US": { "standard": "es-US-Standard-A", "neural2": "es-US-Neural2-A", "chirp3_hd": "es-US-Chirp3-HD-Kore" },
    "et-EE": { "standard": "et-EE-Standard-A" },
    "eu-ES": { "standard": "eu-ES-Standard-A" },
    "fi-FI": { "standard": "fi-FI-Standard-A", "neural2": "fi-FI-Wavenet-A" },
    "fil-PH": { "standard": "fil-PH-Standard-A", "neural2": "fil-PH-Wavenet-A" },
    "fr-CA": { "standard": "fr-CA-Standard-A", "neural2": "fr-CA-Neural2-A", "chirp3_hd": "fr-CA-Chirp3-HD-Kore" },
    "fr-FR": { "standard": "fr-FR-Standard-A", "neural2": "fr-FR-Neural2-A", "chirp3_hd": "fr-FR-Chirp3-HD-Kore" },
    "gl-ES": { "standard": "gl-ES-Standard-A" },
    "gu-IN": { "standard": "gu-IN-Standard-A", "neural2": "gu-IN-Wavenet-A" },
    "he-IL": { "standard": "he-IL-Standard-A", "neural2": "he-IL-Wavenet-A" },
    "hi-IN": { "standard": "hi-IN-Standard-A", "neural2": "hi-IN-Neural2-A", "chirp3_hd": "hi-IN-Chirp3-HD-Kore" },
    "hu-HU": { "standard": "hu-HU-Standard-A", "neural2": "hu-HU-Wavenet-A" },
    "id-ID": { "standard": "id-ID-Standard-A", "neural2": "id-ID-Wavenet-A", "chirp3_hd": "id-ID-Chirp3-HD-Kore" },
    "is-IS": { "standard": "is-IS-Standard-A" },
    "it-IT": { "standard": "it-IT-Standard-A", "neural2": "it-IT-Neural2-A", "chirp3_hd": "it-IT-Chirp3-HD-Kore" },
    "ja-JP": { "standard": "ja-JP-Standard-A", "neural2": "ja-JP-Neural2-B", "chirp3_hd": "ja-JP-Chirp3-HD-Kore" },
    "kn-IN": { "standard": "kn-IN-Standard-A", "neural2": "kn-IN-Wavenet-A" },
    "ko-KR": { "standard": "ko-KR-Standard-A", "neural2": "ko-KR-Neural2-A", "chirp3_hd": "ko-KR-Chirp3-HD-Kore" },
    "lt-LT": { "standard": "lt-LT-Standard-A" },
    "lv-LV": { "standard": "lv-LV-Standard-A" },
    "ml-IN": { "standard": "ml-IN-Standard-A", "neural2": "ml-IN-Wavenet-A" },
    "mr-IN": { "standard": "mr-IN-Standard-A", "neural2": "mr-IN-Wavenet-A" },
    "ms-MY": { "standard": "ms-MY-Standard-A", "neural2": "ms-MY-Wavenet-A" },
    "nb-NO": { "standard": "nb-NO-Standard-A", "neural2": "nb-NO-Wavenet-A" },
    "nl-NL": { "standard": "nl-NL-Standard-A", "neural2": "nl-NL-Wavenet-A", "chirp3_hd": "nl-NL-Chirp3-HD-Kore" },
    "pa-IN": { "standard": "pa-IN-Standard-A", "neural2": "pa-IN-Wavenet-A" },
    "pl-PL": { "standard": "pl-PL-Standard-A", "neural2": "pl-PL-Neural2-A", "chirp3_hd": "pl-PL-Chirp3-HD-Kore" },
    "pt-BR": { "standard": "pt-BR-Standard-A", "neural2": "pt-BR-Neural2-A", "chirp3_hd": "pt-BR-Chirp3-HD-Kore" },
    "pt-PT": { "standard": "pt-PT-Standard-A", "neural2": "pt-PT-Wavenet-A" },
    "ro-RO": { "standard": "ro-RO-Standard-A", "neural2": "ro-RO-Wavenet-A" },
    "ru-RU": { "standard": "ru-RU-Standard-A", "neural2": "ru-RU-Neural2-A", "chirp3_hd": "ru-RU-Chirp3-HD-Kore" },
    "sk-SK": { "standard": "sk-SK-Standard-A", "neural2": "sk-SK-Wavenet-A" },
    "sr-RS": { "standard": "sr-RS-Standard-A" },
    "sv-SE": { "standard": "sv-SE-Standard-A", "neural2": "sv-SE-Wavenet-A", "chirp3_hd": "sv-SE-Chirp3-HD-Kore" },
    "ta-IN": { "standard": "ta-IN-Standard-A", "neural2": "ta-IN-Wavenet-A" },
    "te-IN": { "standard": "te-IN-Standard-A" },
    "th-TH": { "standard": "th-TH-Standard-A", "neural2": "th-TH-Neural2-C", "chirp3_hd": "th-TH-Chirp3-HD-Kore" },
    "tr-TR": { "standard": "tr-TR-Standard-A", "neural2": "tr-TR-Wavenet-A", "chirp3_hd": "tr-TR-Chirp3-HD-Kore" },
    "uk-UA": { "standard": "uk-UA-Standard-A", "neural2": "uk-UA-Wavenet-A" },
    "vi-VN": { "standard": "vi-VN-Standard-A", "neural2": "vi-VN-Neural2-A", "chirp3_hd": "vi-VN-Chirp3-HD-Kore" },
    // Regional Mappings (Critical for invalid argument fix)
    "es-MX": { "standard": "es-US-Standard-A", "neural2": "es-US-Neural2-A", "chirp3_hd": "es-US-Chirp3-HD-Kore" }, // Map MX to US
    "af-ZA": { "standard": "af-ZA-Standard-A" },
};
